mongodb:
    image: 'mongo:5.0.28'
    container_name: 'mongo-db'
    environment:
        - PUID=1000
        - PGID=1000
        - MONGO_INITDB_ROOT_USERNAME=mongoadmin
        - MONGO_INITDB_ROOT_PASSWORD=o8uHQQRKEaMrnFT2kZb8
    volumes:
        - '/home/ubuntu/docker-volume/mongo-db/db:/data/db'
        - '/home/ubuntu/docker-volume/mongo-db/configdb:/data/configdb'
    restart: unless-stopped